log:
  level: INFO
api:
  dashboard: true
  insecure: true
entryPoints:
  websecure:
    address: ":8443"
    http:
      tls:
        options: mkcert-tls
providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
# using mkcert (no acme)
tls:
  options:
    mkcert-tls:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"